#!/usr/bin/env sh
set -eu

export PI_HOLE_SCRIPT_DIR=/opt/pihole
export PI_HOLE_BIN_DIR="${SNAP}/bin"
export PIHOLE_COMMAND="${SNAP}/bin/pihole"
export PATH="${SNAP}/bin:${SNAP}/usr/bin:${PATH}"

"${SNAP}/bin/pihole-bootstrap"
exec "${SNAP}/usr/bin/pihole-FTL" -f

